# Generated by Django 4.0.8 on 2022-11-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0002_department_level_alter_option_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
    ]
